import {
  BadgeDollarSign,
  Castle,
  Contact,
  GlobeIcon,
  Heart,
  Hotel,
  MapPinned,
  MoonStar,
  Palette,
  PersonStanding,
  Sailboat,
  ShoppingBag,
  Sparkles,
  Users2,
} from "lucide-react";

export const links = [
  {
    title: "Home",
    href: "/dashboard",
  },
  {
    title: "Settings",
    href: "/dashboard/settings",
  },
];

export const budgetList = [
  {
    id: "low",
    label: "Low",
    value: "low",
    description: "Budget Around 0-3,000,000 (IDR)",
  },
  {
    id: "medium",
    label: "Medium",
    value: "medium",
    description: "Budget Around 3,000,000-5,000,000 (IDR)",
  },
  {
    id: "high",
    label: "High",
    value: "high",
    description: "Budget Around 5,000,000+ (IDR)",
  },
  {
    id: "custom",
    label: "Custom",
    value: "custom",
    description: "Custom budget what you want in (IDR)",
  },
];

export const ACTIVITY_PREFERENCES = [
  { id: "sightseeing", displayName: "Sightseeing", icon: MapPinned },
  { id: "adventure", displayName: "Adventure", icon: Sailboat },
  {
    id: "culturalexperiences",
    displayName: "Cultural Experiences",
    icon: Palette,
  },
  { id: "historical", displayName: "Historical", icon: Castle },
  { id: "relaxationwellness", displayName: "Relaxation", icon: PersonStanding },
  { id: "shopping", displayName: "Shopping", icon: ShoppingBag },
  { id: "nightlife", displayName: "Nightlife", icon: MoonStar },
];

export const COMPANION_PREFERENCES = [
  { id: "solo", displayName: "Solo", icon: MapPinned },
  { id: "couple", displayName: "Couple", icon: Heart },
  { id: "family", displayName: "Family", icon: Users2 },
  { id: "group", displayName: "Group", icon: Contact },
];

export const globeConfig = {
  pointSize: 4,
  globeColor: "#7ECE94",
  showAtmosphere: true,
  atmosphereColor: "#fff",
  atmosphereAltitude: 0.1,
  emissive: "#062056",
  emissiveIntensity: 0.1,
  shininess: 0.9,
  polyhonColor: "rgba(255, 255, 255, 0.7)",
  AmbientLight: "#38bdff",
  directionalLeftLight: "#fff",
  directionalTopLight: "#fff",
  pointLights: "#fff",
  arcTime: 2000,
  arcLength: 0.9,
  rings: 0.5,
  maxRings: 0.5,
  initialPosition: {
    lat: -6.899528076912856,
    lng: 107.61963905551623,
  },
  autoRotate: true,
  autoRotateSpeed: 0.5,
};

export const colors = ["#00FF00", "#0000FF", "#FFFF00", "#FF00FF", "#00FFFF"];

export const sampleDataArcs = [
  {
    order: 1,
    startLat: 37.7749,
    startLng: -122.4194,
    endLat: 34.0522,
    endLng: -118.2437,
    arcAlt: 0.15,
    color: colors[Math.floor(Math.random() * colors.length)],
  },
  {
    order: 2,
    startLat: 51.5074,
    startLng: -0.1278,
    endLat: 40.7128,
    endLng: -74.006,
    arcAlt: 0.25,
    color: colors[Math.floor(Math.random() * colors.length)],
  },
  {
    order: 3,
    startLat: 35.6895,
    startLng: 139.6917,
    endLat: -33.8688,
    endLng: 151.2093,
    arcAlt: 0.3,
    color: colors[Math.floor(Math.random() * colors.length)],
  },
  {
    order: 4,
    startLat: 48.8566,
    startLng: 2.3522,
    endLat: 55.7558,
    endLng: 37.6173,
    arcAlt: 0.2,
    color: colors[Math.floor(Math.random() * colors.length)],
  },
  {
    order: 5,
    startLat: -34.6037,
    startLng: -58.3816,
    endLat: -22.9068,
    endLng: -43.1729,
    arcAlt: 0.18,
    color: colors[Math.floor(Math.random() * colors.length)],
  },
  {
    order: 6,
    startLat: 19.076,
    startLng: 72.8777,
    endLat: 35.6762,
    endLng: 139.6503,
    arcAlt: 0.35,
    color: colors[Math.floor(Math.random() * colors.length)],
  },
  {
    order: 7,
    startLat: -33.9249,
    startLng: 18.4241,
    endLat: -23.5505,
    endLng: -46.6333,
    arcAlt: 0.28,
    color: colors[Math.floor(Math.random() * colors.length)],
  },
  {
    order: 8,
    startLat: 40.4168,
    startLng: -3.7038,
    endLat: 41.9028,
    endLng: 12.4964,
    arcAlt: 0.22,
    color: colors[Math.floor(Math.random() * colors.length)],
  },
  {
    order: 9,
    startLat: 55.7558,
    startLng: 37.6173,
    endLat: 35.6895,
    endLng: 139.6917,
    arcAlt: 0.32,
    color: colors[Math.floor(Math.random() * colors.length)],
  },
  {
    order: 10,
    startLat: 52.52,
    startLng: 13.405,
    endLat: 59.3293,
    endLng: 18.0686,
    arcAlt: 0.26,
    color: colors[Math.floor(Math.random() * colors.length)],
  },
  {
    order: 11,
    startLat: 31.2304,
    startLng: 121.4737,
    endLat: 39.9042,
    endLng: 116.4074,
    arcAlt: 0.27,
    color: colors[Math.floor(Math.random() * colors.length)],
  },
  {
    order: 12,
    startLat: -37.8136,
    startLng: 144.9631,
    endLat: -33.8688,
    endLng: 151.2093,
    arcAlt: 0.19,
    color: colors[Math.floor(Math.random() * colors.length)],
  },
  {
    order: 13,
    startLat: 22.3964,
    startLng: 114.1095,
    endLat: 34.6937,
    endLng: 135.5023,
    arcAlt: 0.21,
    color: colors[Math.floor(Math.random() * colors.length)],
  },
  {
    order: 14,
    startLat: 30.0444,
    startLng: 31.2357,
    endLat: 25.276987,
    endLng: 55.296249,
    arcAlt: 0.34,
    color: colors[Math.floor(Math.random() * colors.length)],
  },
  {
    order: 15,
    startLat: 59.9343,
    startLng: 30.3351,
    endLat: 55.7558,
    endLng: 37.6173,
    arcAlt: 0.23,
    color: colors[Math.floor(Math.random() * colors.length)],
  },
  {
    order: 16,
    startLat: 45.4654,
    startLng: 9.1859,
    endLat: 41.9028,
    endLng: 12.4964,
    arcAlt: 0.29,
    color: colors[Math.floor(Math.random() * colors.length)],
  },
  {
    order: 17,
    startLat: 23.1291,
    startLng: 113.2644,
    endLat: 31.2304,
    endLng: 121.4737,
    arcAlt: 0.3,
    color: colors[Math.floor(Math.random() * colors.length)],
  },
  {
    order: 18,
    startLat: 37.5665,
    startLng: 126.978,
    endLat: 35.6762,
    endLng: 139.6503,
    arcAlt: 0.33,
    color: colors[Math.floor(Math.random() * colors.length)],
  },
  {
    order: 19,
    startLat: 40.7306,
    startLng: -73.9352,
    endLat: 34.0522,
    endLng: -118.2437,
    arcAlt: 0.24,
    color: colors[Math.floor(Math.random() * colors.length)],
  },
  {
    order: 20,
    startLat: 43.6532,
    startLng: -79.3832,
    endLat: 45.5017,
    endLng: -73.5673,
    arcAlt: 0.22,
    color: colors[Math.floor(Math.random() * colors.length)],
  },
  {
    order: 21,
    startLat: 50.1109,
    startLng: 8.6821,
    endLat: 48.8566,
    endLng: 2.3522,
    arcAlt: 0.17,
    color: colors[Math.floor(Math.random() * colors.length)],
  },
  {
    order: 22,
    startLat: -26.2041,
    startLng: 28.0473,
    endLat: -34.6037,
    endLng: -58.3816,
    arcAlt: 0.3,
    color: colors[Math.floor(Math.random() * colors.length)],
  },
  {
    order: 23,
    startLat: 39.9042,
    startLng: 116.4074,
    endLat: 22.3964,
    endLng: 114.1095,
    arcAlt: 0.31,
    color: colors[Math.floor(Math.random() * colors.length)],
  },
  {
    order: 24,
    startLat: 13.7563,
    startLng: 100.5018,
    endLat: 1.3521,
    endLng: 103.8198,
    arcAlt: 0.35,
    color: colors[Math.floor(Math.random() * colors.length)],
  },
  {
    order: 25,
    startLat: 25.276987,
    startLng: 55.296249,
    endLat: 21.3891,
    endLng: 39.8579,
    arcAlt: 0.25,
    color: colors[Math.floor(Math.random() * colors.length)],
  },
];

export const features = [
  {
    title: "AI-Powered Travel Planning",
    description:
      "Effortlessly create detailed travel plans in seconds. Let our advanced AI tailor your trip to perfection, so you can focus on enjoying the journey.",
    icon: GlobeIcon,
  },
  {
    title: "Handpicked Hotels & Itinerary",
    description:
      "Discover the best accommodations and activities with our AI-curated recommendations, ensuring every moment of your trip is perfectly planned.",
    icon: Hotel,
  },
  {
    title: "Cutting-Edge AI & API Integration",
    description:
      "Experience the future of travel with our top-tier AI engine, seamlessly integrated with leading travel APIs for unparalleled accuracy and convenience.",
    icon: Sparkles,
  },
  {
    title: "Completely Free, Always",
    description:
      "Enjoy all the benefits of our AI travel planner without any cost. No hidden fees, just hassle-free planning at your fingertips.",
    icon: BadgeDollarSign,
  },
];

export const reviews = [
  {
    name: "Jack",
    username: "@jack",
    body: "I love how easy it is to plan my trips with this app. It's like having a personal travel assistant in my pocket!",
    img: "https://avatar.vercel.sh/rauchg.svg?text=J",
  },
  {
    name: "Emily",
    username: "@emily",
    body: "The AI recommendations are spot on. I found hidden gems I wouldn't have discovered otherwise.",
    img: "https://avatar.vercel.sh/nesquik.svg?text=E",
  },
  {
    name: "Oliver",
    username: "@oliver",
    body: "Planning a complex trip has never been simpler. The interface is intuitive and saves me so much time.",
    img: "https://avatar.vercel.sh/rauchg.svg?text=O",
  },
  {
    name: "Sophia",
    username: "@sophia",
    body: "Fantastic app! It made organizing my vacation a breeze, and the suggestions were incredibly helpful.",
    img: "https://avatar.vercel.sh/nesquik.svg?text=S",
  },
  {
    name: "Liam",
    username: "@liam",
    body: "I appreciate how the app customizes travel plans to my preferences. It's like having a personal travel concierge.",
    img: "https://avatar.vercel.sh/rauchg.svg?text=L",
  },
  {
    name: "Ava",
    username: "@ava",
    body: "The app's ability to integrate flights, hotels, and activities into one plan is amazing. I highly recommend it!",
    img: "https://avatar.vercel.sh/nesquik.svg?text=A",
  },
  {
    name: "Noah",
    username: "@noah",
    body: "I used to struggle with travel planning, but this app has made it so much easier. The AI is incredibly smart.",
    img: "https://avatar.vercel.sh/rauchg.svg?text=N",
  },
  {
    name: "Isabella",
    username: "@isabella",
    body: "A game-changer for anyone who loves to travel. The app's recommendations are always on point.",
    img: "https://avatar.vercel.sh/nesquik.svg?text=I",
  },
  {
    name: "Mason",
    username: "@mason",
    body: "Easy to use and incredibly effective. My trips are now well-organized and stress-free thanks to this app.",
    img: "https://avatar.vercel.sh/rauchg.svg?text=M",
  },
  {
    name: "Mia",
    username: "@mia",
    body: "I’m impressed by how the app personalizes my travel plans. It’s like having a tailored travel guide.",
    img: "https://avatar.vercel.sh/nesquik.svg?text=M",
  },
  {
    name: "Ethan",
    username: "@ethan",
    body: "The app has made travel planning a pleasure. The AI’s suggestions are always relevant and useful.",
    img: "https://avatar.vercel.sh/rauchg.svg?text=E",
  },
  {
    name: "Charlotte",
    username: "@charlotte",
    body: "I love the detailed itineraries and easy booking process. This app takes the hassle out of travel planning.",
    img: "https://avatar.vercel.sh/nesquik.svg?text=C",
  },
  {
    name: "James",
    username: "@james",
    body: "This app has revolutionized the way I plan my trips. The AI does all the heavy lifting for me.",
    img: "https://avatar.vercel.sh/rauchg.svg?text=J",
  },
  {
    name: "Amelia",
    username: "@amelia",
    body: "Amazing tool for organizing travel. The app’s suggestions and features are top-notch!",
    img: "https://avatar.vercel.sh/nesquik.svg?text=A",
  },
  {
    name: "Benjamin",
    username: "@benjamin",
    body: "Incredibly useful app for anyone who travels frequently. It takes care of everything so I can focus on enjoying my trips.",
    img: "https://avatar.vercel.sh/rauchg.svg?text=B",
  },
  {
    name: "Harper",
    username: "@harper",
    body: "The app’s interface is sleek and user-friendly. Planning my next trip has never been this easy.",
    img: "https://avatar.vercel.sh/nesquik.svg?text=H",
  },
  {
    name: "Jacob",
    username: "@jacob",
    body: "Highly recommend this app for seamless travel planning. The AI’s recommendations are always spot on.",
    img: "https://avatar.vercel.sh/rauchg.svg?text=J",
  },
  {
    name: "Ella",
    username: "@ella",
    body: "I’m impressed with the level of detail and personalization in the travel plans. It makes planning a joy.",
    img: "https://avatar.vercel.sh/nesquik.svg?text=E",
  },
  {
    name: "Michael",
    username: "@michael",
    body: "This app simplifies every aspect of travel planning. I love how it handles everything for me.",
    img: "https://avatar.vercel.sh/rauchg.svg?text=M",
  },
  {
    name: "Abigail",
    username: "@abigail",
    body: "I can’t imagine planning trips without this app now. It’s a lifesaver for managing all my travel details.",
    img: "https://avatar.vercel.sh/nesquik.svg?text=A",
  },
  {
    name: "Elijah",
    username: "@elijah",
    body: "The app’s AI does a fantastic job of curating personalized travel itineraries. It’s like having a travel expert on call.",
    img: "https://avatar.vercel.sh/rauchg.svg?text=E",
  },
  {
    name: "Scarlett",
    username: "@scarlett",
    body: "Effortless travel planning! The app’s suggestions and features make organizing trips a breeze.",
    img: "https://avatar.vercel.sh/nesquik.svg?text=S",
  },
  {
    name: "Alexander",
    username: "@alexander",
    body: "I’ve tried many travel apps, but this one stands out. It simplifies planning and delivers great results.",
    img: "https://avatar.vercel.sh/rauchg.svg?text=A",
  },
  {
    name: "Sofia",
    username: "@sofia",
    body: "This app is a must-have for anyone who travels. It makes planning and booking so much easier.",
    img: "https://avatar.vercel.sh/nesquik.svg?text=S",
  },
  {
    name: "Daniel",
    username: "@daniel",
    body: "The best travel planning app I’ve used. The AI provides accurate and helpful suggestions every time.",
    img: "https://avatar.vercel.sh/rauchg.svg?text=D",
  },
  {
    name: "Grace",
    username: "@grace",
    body: "I love how the app integrates all aspects of my trip. It’s efficient, user-friendly, and reliable.",
    img: "https://avatar.vercel.sh/nesquik.svg?text=G",
  },
  {
    name: "Henry",
    username: "@henry",
    body: "The app’s personalized travel plans have made my trips so much more enjoyable. Highly recommend!",
    img: "https://avatar.vercel.sh/rauchg.svg?text=H",
  },
  {
    name: "Chloe",
    username: "@chloe",
    body: "Planning my trips is now so much easier. The app’s AI does a great job of handling all the details.",
    img: "https://avatar.vercel.sh/nesquik.svg?text=C",
  },
  {
    name: "Lucas",
    username: "@lucas",
    body: "This app has streamlined my travel planning like never before. The AI recommendations are a game-changer!",
    img: "https://avatar.vercel.sh/rauchg.svg?text=L",
  },
  {
    name: "Zoe",
    username: "@zoe",
    body: "I’m blown away by how easy it is to use this app. It takes the stress out of planning and lets me focus on enjoying my trips.",
    img: "https://avatar.vercel.sh/nesquik.svg?text=Z",
  },
  {
    name: "Ryan",
    username: "@ryan",
    body: "The app’s intelligent suggestions have made a huge difference in my travel experiences. It’s now my go-to travel planner.",
    img: "https://avatar.vercel.sh/rauchg.svg?text=R",
  },
  {
    name: "Nora",
    username: "@nora",
    body: "From booking flights to finding local attractions, this app does it all. I’m really impressed with its capabilities.",
    img: "https://avatar.vercel.sh/nesquik.svg?text=N",
  },
  {
    name: "William",
    username: "@william",
    body: "If you’re looking for a reliable travel planning tool, this is it. The app’s efficiency and accuracy are unmatched.",
    img: "https://avatar.vercel.sh/rauchg.svg?text=W",
  },
];
